name: mindbreeze
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  visibility_detector: ^0.4.0+2

  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  
  assets:
    - res/icons/calendar.png
    - res/icons/un_calendar.png
    - res/icons/logo.png
    - res/icons/circle_button.png
    - res/icons/sad.png
    - res/icons/amazed.png
    - res/icons/angry.png
    - res/icons/anxious.png
    - res/icons/broken.png
    - res/icons/calm.png
    - res/icons/done.png
    - res/icons/done_background.png
    - res/icons/plus.png
    - res/icons/bin.png

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
